export const initialGrades = [[
  { grade: "A+", point: 4.25 },
  { grade: "A", point: 4.0 },
  { grade: "A-", point: 3.75 },
  { grade: "B+", point: 3.25 },
  { grade: "B", point: 3.0 },
  { grade: "B-", point: 2.75 },
  { grade: "C+", point: 2.25 },
  { grade: "C", point: 2.00 },
  { grade: "C-", point: 1.75 },
  { grade: "D+", point: 1.25 },
  { grade: "D", point: 1.00 },
  { grade: "D-", point: 0.75 },
  { grade: "E", point: 0.00 },
  { grade: "NC", point: 0.00 },
]]